version: "3.9"

services:
  civit_browser:
    container_name: "civit_browser"
    image: ghcr.io/martokk/civit_browser:latest
    restart: unless-stopped
    volumes:
      # - /home/ubuntu/volumes/civit_browser/data:/civit_browser/data
      - ./app:/app
    ports:
      - "5000:5000"
