version: "3.9"

services:
  python_fastapi_stack:
    container_name: "python_fastapi_stack"
    image: ghcr.io/martokk/python_fastapi_stack:latest
    restart: unless-stopped
    volumes:
      # - /home/ubuntu/volumes/python_fastapi_stack/data:/python_fastapi_stack/data
      - ./app:/app
    ports:
      - "5000:5000"
