"""removed images

Revision ID: 2077e2a2e360
Revises: b08c4e65c8af
Create Date: 2024-11-25 19:35:49.631301

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '2077e2a2e360'
down_revision = 'b08c4e65c8af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
