"""removed images

Revision ID: b08c4e65c8af
Revises: c6eb16076fe1
Create Date: 2024-11-25 19:34:32.768723

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'b08c4e65c8af'
down_revision = 'c6eb16076fe1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
