"""removed images

Revision ID: c6eb16076fe1
Revises: 20240101_add_page_number
Create Date: 2024-11-25 19:31:24.654450

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'c6eb16076fe1'
down_revision = '20240101_add_page_number'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('url', sa.VARCHAR(), nullable=True),
    sa.Column('owner_id', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name='fk_images_owner_id_user'),
    sa.PrimaryKeyConstraint('id', name='pk_images')
    )
    # ### end Alembic commands ###
